# Generated by Django 4.1.6 on 2023-02-19 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="address",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="city",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="state",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="patient",
            name="heartrate",
            field=models.IntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                ]
            ),
        ),
    ]
